services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

  ollama-init:
    image: ollama/ollama
    container_name: ollama-init
    depends_on:
      - ollama
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    command: >
      sh -c "
        echo 'Waiting for Ollama server...' &&
        while ! curl -s http://ollama:11434/api/tags > /dev/null; do sleep 2; done &&
        echo 'Ollama server is ready!' &&
        echo 'Pulling llama3.2:1b model...' &&
        ollama pull llama3.2:1b &&
        echo 'Testing model...' &&
        ollama run llama3.2:1b 'Hello, test message' &&
        echo 'Model setup complete!'
      "
    restart: "no"

  ai-review-app:
    build: .
    container_name: ai-review-app
    ports:
      - "3000:3000"
    depends_on:
      - ollama-init
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:1b
      - NODE_ENV=development
      - NODE_OPTIONS=--experimental-fetch  # If using Node.js < 18
    restart: unless-stopped

volumes:
  ollama_models:
